import { Cell } from '@types';

export const mockCells: Cell[] = [
  { fixed: true, position: { column: 1, line: 0 }, value: 9 },
  { fixed: true, position: { column: 2, line: 0 }, value: 6 },
  { fixed: true, position: { column: 4, line: 0 }, value: 2 },
  { fixed: true, position: { column: 6, line: 0 }, value: 5 },
  { fixed: true, position: { column: 7, line: 0 }, value: 4 },
  { fixed: true, position: { column: 1, line: 1 }, value: 4 },
  { fixed: true, position: { column: 2, line: 1 }, value: 2 },
  { fixed: true, position: { column: 4, line: 1 }, value: 5 },
  { fixed: true, position: { column: 6, line: 1 }, value: 8 },
  { fixed: true, position: { column: 8, line: 1 }, value: 7 },
  { fixed: true, position: { column: 2, line: 2 }, value: 1 },
  { fixed: true, position: { column: 2, line: 3 }, value: 7 },
  { fixed: true, position: { column: 4, line: 3 }, value: 8 },
  { fixed: true, position: { column: 8, line: 3 }, value: 9 },
  { fixed: true, position: { column: 1, line: 4 }, value: 5 },
  { fixed: true, position: { column: 3, line: 4 }, value: 3 },
  { fixed: true, position: { column: 4, line: 4 }, value: 1 },
  { fixed: true, position: { column: 7, line: 4 }, value: 8 },
  { fixed: true, position: { column: 1, line: 5 }, value: 6 },
  { fixed: true, position: { column: 7, line: 5 }, value: 2 },
  { fixed: true, position: { column: 5, line: 6 }, value: 2 },
  { fixed: true, position: { column: 6, line: 6 }, value: 1 },
  { fixed: true, position: { column: 7, line: 6 }, value: 9 },
  { fixed: true, position: { column: 1, line: 7 }, value: 1 },
  { fixed: true, position: { column: 2, line: 8 }, value: 8 },
  { fixed: true, position: { column: 3, line: 8 }, value: 1 },
  { fixed: true, position: { column: 4, line: 8 }, value: 7 },
  { fixed: true, position: { column: 6, line: 8 }, value: 6 },
  { fixed: true, position: { column: 7, line: 8 }, value: 3 },
];
